[package]
name = "solana-http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
serde = { version = "1.0", features = ["derive"] }
solana-sdk = "1.18.0"
spl-token = "4.0.0"
base64 = "0.21.5"
bs58 = "0.5.1"